from __future__ import annotations

import time
from concurrent.futures import Future, ThreadPoolExecutor
from datetime import datetime

from codex_autonomy.config import ManagerConfig
from codex_autonomy.github_flow import try_merge_pr
from codex_autonomy.health import run_health_checks
from codex_autonomy.models import TaskSpec, TaskStatus
from codex_autonomy.state_db import init_db, log_event
from codex_autonomy.task_store import archive_task, dependency_satisfied, load_tasks, save_task
from codex_autonomy.worker import run_task


class AutonomyManager:
    def __init__(self, config: ManagerConfig):
        self.config = config
        self.executor = ThreadPoolExecutor(max_workers=config.max_parallel_workers)
        self.inflight: dict[str, Future] = {}
        self.last_health_check = 0.0

    def _select_runnable_tasks(self, tasks: list[TaskSpec]) -> list[TaskSpec]:
        now_ts = int(time.time())
        by_id = {t.task_id: t for t in tasks}
        runnable: list[TaskSpec] = []
        for task in tasks:
            if task.status != TaskStatus.PENDING:
                continue
            not_before = int(task.metadata.get("not_before_epoch", 0) or 0)
            if not_before > now_ts:
                continue
            if task.task_id in self.inflight:
                continue
            if dependency_satisfied(task, by_id):
                runnable.append(task)
        runnable.sort(key=lambda t: (t.priority, t.created_at))
        return runnable

    def _handle_finished(self) -> None:
        done_ids: list[str] = []
        for task_id, future in self.inflight.items():
            if not future.done():
                continue
            done_ids.append(task_id)
            result = future.result()
            now = datetime.utcnow().isoformat()
            log_event(
                self.config.state_db_path,
                ts=now,
                task_id=task_id,
                event_type="task_result",
                message=f"{result.status.value}: {result.message}",
            )
            if result.status in {TaskStatus.COMPLETED, TaskStatus.FAILED}:
                archive_task(self.config.queue_dir, self.config.archive_dir, task_id)

        for task_id in done_ids:
            self.inflight.pop(task_id, None)

    def _advance_review_tasks(self, tasks: list[TaskSpec]) -> None:
        for task in tasks:
            if task.status != TaskStatus.REVIEW:
                continue
            if task.pr_number is None:
                continue
            if not self.config.github.auto_merge:
                continue
            merged = try_merge_pr(self.config, task.pr_number)
            if not merged:
                continue
            task.status = TaskStatus.COMPLETED
            save_task(self.config.queue_dir, task)
            archive_task(self.config.queue_dir, self.config.archive_dir, task.task_id)
            log_event(
                self.config.state_db_path,
                ts=datetime.utcnow().isoformat(),
                task_id=task.task_id,
                event_type="pr_merged",
                message=f"merged PR #{task.pr_number}",
            )

    def run_forever(self) -> None:
        init_db(self.config.state_db_path)
        self.config.queue_dir.mkdir(parents=True, exist_ok=True)
        self.config.archive_dir.mkdir(parents=True, exist_ok=True)
        self.config.runtime_dir.mkdir(parents=True, exist_ok=True)

        while True:
            self._handle_finished()

            now_ts = time.time()
            if (
                self.config.enable_health_loop
                and now_ts - self.last_health_check >= self.config.health.interval_seconds
            ):
                created = run_health_checks(self.config)
                self.last_health_check = now_ts
                for task_id in created:
                    log_event(
                        self.config.state_db_path,
                        ts=datetime.utcnow().isoformat(),
                        task_id=task_id,
                        event_type="health_generated",
                        message="auto-generated by health loop",
                    )

            tasks = load_tasks(self.config.queue_dir)
            self._advance_review_tasks(tasks)
            tasks = load_tasks(self.config.queue_dir)
            runnable = self._select_runnable_tasks(tasks)
            free_slots = self.config.max_parallel_workers - len(self.inflight)

            for task in runnable[: max(0, free_slots)]:
                fut = self.executor.submit(run_task, self.config, task)
                self.inflight[task.task_id] = fut
                log_event(
                    self.config.state_db_path,
                    ts=datetime.utcnow().isoformat(),
                    task_id=task.task_id,
                    event_type="task_started",
                    message="worker launched",
                )

            time.sleep(self.config.poll_interval_seconds)
